export { HomePage } from "./homepage";
export { OurVision } from "./about-us/our-vision";
export { OurStrengths } from "./about-us/our-strengths";
export { WhyChoose5dVr } from "./about-us/why-choose-5dvr";
export { FeaturedProjects } from "./portfolio/featured-projects";
export { VirtualReality } from "./services";
export { AugmentedReality } from "./services";
export { MixedReality } from "./services";
export { AIPoweredXRSolutions } from "./services";
export { _360PhotographyAndVideoGraphic } from "./services";
export { _3DModelingAndAnimation } from "./services";
export { InteractiveInstallations } from "./services";
export { TrainingAndCourses } from "./services";
export * from "./sector-industries";
export * from "./portfolio";
